### ISSUE TITLE
About the corpus

### ISSUE THREAD

**Issue by lale314** [megagonlabs/ginza#103]
Can you show me a sample corpus of the named entity recognition models?

**Comment by hiroshi-matsuda-rit** [comment]
@lale314 Sorry for late reply. I'm preparing a publicly available dataset which contains NER gold labels with gold dependencies.
I'd like to report you as soon as UD_Japanese-GSD v2.6-NE released.

**Comment by hiroshi-matsuda-rit** [comment]
We've published UD_Japanese-GSD v2.6-NE and converted (train,dev,test) files as JSON file format which `spacy train` takes.
https://github.com/megagonlabs/UD_Japanese-GSD/blob/master/ja_gsd-ud-train.ne.json .

We apply these options for `spacy train` like:
`$ python -m spacy train ja ja_gsd-2.2.6 ja_gsd-ud-train.ne.json ja_gsd-ud-dev.ne.json -v ja_vectors_chive_mc90_a-unit-only/ -pt tag,dep,ent -et tag,dep,ent --learn-token -ovl 0.05 -n 300 -V 2.2.6`

GiNZA is trained with almost the same options.
