### ISSUE TITLE
How to use ginzame via Python

### ISSUE THREAD

**Issue by MokkeMeguru** [megagonlabs/ginza#105]
Hello!
I want to use ginza/ginzame for Japanese corpus's preprocessing like MeCab.

But I have a question. 
I think you only showed the example of using ginza. I'd not found the example of using ginzame. 

Can you add the example of using ginzame?

**Comment by hiroshi-matsuda-rit** [comment]
Hi @MokkeMeguru ,
Thank you for asking the mecab mode.
I'd like to add an introduction to run only the morphological analysis part and the parallelizing method used in ginzame command.
Please read the souce code of ginza.command_line right now.
https://github.com/megagonlabs/ginza/blob/develop/ginza/command_line.py

**Comment by MokkeMeguru** [comment]
OK, I'll read the code.
Can I keep opening the issue because I'd not already write the code?
If I have any question, I'll add the comment in this issue.

**Comment by MokkeMeguru** [comment]
Thanks!

I wrote the code to use ginzame ! 
https://github.com/MokkeMeguru/meguru_tokenizer/blob/master/japanese/tokenize_sudachi.py
