### ISSUE TITLE
Email entity issue

### ISSUE THREAD

**Issue by RobinXL** [megagonlabs/ginza#106]
So I was testing training on some data, and I got ValueError indicates contaminated data.
Then I found some email contains dot will generate error(before @).
for example:
```('hello.world@gmail.com',{'entities':[(0, 21, 'EMAIL')]})  # doesnt work```
```('helloworld@gmail.com',{'entities':[(0, 20, 'EMAIL')]}) # works```

Any idea why it happened?

**Comment by hiroshi-matsuda-rit** [comment]
Thanks @RobinXL 
I'm surfacing same kind of error related while training NER.
I found these kinds of NE context including period between alphabetical tokens cause errors in spacy train command.
```
James P.Gordon
mmap.info
```

I reported this problem at this issue. https://github.com/explosion/spaCy/issues/3756#issuecomment-627344482

**Comment by hiroshi-matsuda-rit** [comment]
Hi @RobinXL 
I found this error is coming from spaCy's CNN trainer.
Let us wait the major version up of spaCy.
I'd close this issue.
