### ISSUE TITLE
Misplaced BunsetuBILabel=I on 連体詞

### ISSUE THREAD

**Issue by KoichiYasuoka** [megagonlabs/ginza#108]
I've just tried a sentence "いずれその話をしよう" with GiNZA, and got the result below:

```
# text = いずれその話をしよう
1       いずれ  いずれ  ADV     副詞    _       5       dep     _       BunsetuBILabel=B|BunsetuPositionType=SEM_HEAD|SpaceAfter=No
2       その    其の    DET     連体詞  _       3       det     _       BunsetuBILabel=I|BunsetuPositionType=CONT|SpaceAfter=No
3       話      話      NOUN    名詞-普通名詞-サ変可能  _       5       obj    _BunsetuBILabel=B|BunsetuPositionType=SEM_HEAD|SpaceAfter=No|NP_B
4       を      を      ADP     助詞-格助詞     _       3       case    _      BunsetuBILabel=I|BunsetuPositionType=SYN_HEAD|SpaceAfter=No
5       しよう  為る    AUX     動詞-非自立可能 _       0       root    _      BunsetuBILabel=B|BunsetuPositionType=ROOT|SpaceAfter=No
```

「いずれその」「話を」「しよう」 seems wrong cuts of 文節. IMHO it should be 「いずれ」「その」「話を」「しよう」 or 「いずれ」「その話を」「しよう」, and almost all 連体詞 should start 文節 (except for 連体詞 immediately after 補助記号-括弧開).

**Comment by hiroshi-matsuda-rit** [comment]
Thanks @KoichiYasuoka 
I'd try to improve this Bunsetu sengmentation rule in next release of GiNZA.

**Comment by hiroshi-matsuda-rit** [comment]
I'm developing `yield_bunsetu()` in spaCy's official Japanese model issue. https://github.com/explosion/spaCy/issues/3756#issuecomment-632586050
This would solve a kind of problem like you showed above.

**Comment by hiroshi-matsuda-rit** [comment]
We've implemented new analysis model for bunsetu recognition for GiNZA v4. This is the result. 
```
# text = いずれその話をしよう
1       いずれ  いずれ  ADV     副詞    _       5       advmod  _       SpaceAfter=No|BunsetuBILabel=B|BunsetuPositionType=SEM_HEAD|Reading=イズレ
2       その    その    DET     連体詞  _       3       det     _       SpaceAfter=No|BunsetuBILabel=B|BunsetuPositionType=SEM_HEAD|Reading=ソノ
3       話      話      NOUN    名詞-普通名詞-サ変可能  _       5       obj     _       SpaceAfter=No|BunsetuBILabel=B|BunsetuPositionType=SEM_HEAD|NP_B|Reading=ハナシ
4       を      を      ADP     助詞-格助詞     _       3       case    _       SpaceAfter=No|BunsetuBILabel=I|BunsetuPositionType=SYN_HEAD|Reading=ヲ
5       しよう  する    VERB    動詞-非自立可能 _       0       root    _       SpaceAfter=No|BunsetuBILabel=B|BunsetuPositionType=ROOT|Inf=サ行変格,意志推量形|Reading=シヨウ
```
The new bunsetu model can estimate bunsetu-head relations and the spans of bunsetu more accuraltely.
We're very happy if you'd try this model.
Thanks a lot! @KoichiYasuoka

**Comment by KoichiYasuoka** [comment]
I've just written [GiNZA v4.0.0で「いずれその話をしよう」を解析しよう](https://srad.jp/~yasuoka/journal/641174/) in my blog. Thank you @hiroshi-matsuda-rit !

**Comment by hiroshi-matsuda-rit** [comment]
Thank you! @KoichiYasuoka 
I read your blog post.
You can get the iterator of busetu spans by calling ginza.busetu_spans(sent_span).
