### ISSUE TITLE
Getting "ImportError: Japanese support requires SudachiPy distributed with ja language mode" after installing sudachipy and dictionary

### ISSUE THREAD

**Issue by pawar30** [megagonlabs/ginza#112]
I am running Anaconda(2020.02) with python 3.7.6 on Windows 10. I have the following lines of code to load Ginza - 
import spacy
nlp = spacy.load('ja_ginza')

I have also downloaded sudachipy and sudachidict_core as discussed in the issue https://github.com/megagonlabs/ginza/issues/71
However, I still get the "Japanese support requires SudachiPy distributed with ja language model".
Please do let me know if I am missing an import/install. Below is the full stacktrace

ImportError                               Traceback (most recent call last)
~\Anaconda3\lib\site-packages\ginza\sudachipy_tokenizer.py in try_import_sudachipy_dictionary()
     35     try:
---> 36         from sudachipy import dictionary
     37         return dictionary

~\Anaconda3\lib\site-packages\sudachipy\dictionary.py in <module>
     15 from . import config
---> 16 from . import dictionarylib
     17 from .dictionarylib.binarydictionary import BinaryDictionary

~\Anaconda3\lib\site-packages\sudachipy\dictionarylib\__init__.py in <module>
     18 from . import lexiconset
---> 19 from . import doublearraylexicon
     20 from . import dictionaryheader

~\Anaconda3\lib\site-packages\sudachipy\dictionarylib\doublearraylexicon.py in <module>
     16 
---> 17 from dartsclone import DoubleArray
     18 

~\Anaconda3\lib\site-packages\dartsclone\__init__.py in <module>
----> 1 from dartsclone._dartsclone import DoubleArray
      2 
      3 __all__ = [

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-11-68155cf1a72c> in <module>
----> 1 nlp = spacy.load('ja_ginza')

~\Anaconda3\lib\site-packages\spacy\__init__.py in load(name, **overrides)
     28     if depr_path not in (True, False, None):
     29         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 30     return util.load_model(name, **overrides)
     31 
     32 

~\Anaconda3\lib\site-packages\spacy\util.py in load_model(name, **overrides)
    162             return load_model_from_link(name, **overrides)
    163         if is_package(name):  # installed as package
--> 164             return load_model_from_package(name, **overrides)
    165         if Path(name).exists():  # path to model data directory
    166             return load_model_from_path(Path(name), **overrides)

~\Anaconda3\lib\site-packages\spacy\util.py in load_model_from_package(name, **overrides)
    183     """Load a model from an installed package."""
    184     cls = importlib.import_module(name)
--> 185     return cls.load(**overrides)
    186 
    187 

~\Anaconda3\lib\site-packages\ja_ginza\__init__.py in load(**overrides)
     10 
     11 def load(**overrides):
---> 12     return load_model_from_init_py(__file__, **overrides)

~\Anaconda3\lib\site-packages\spacy\util.py in load_model_from_init_py(init_file, **overrides)
    226     if not model_path.exists():
    227         raise IOError(Errors.E052.format(path=path2str(data_path)))
--> 228     return load_model_from_path(data_path, meta, **overrides)
    229 
    230 

~\Anaconda3\lib\site-packages\spacy\util.py in load_model_from_path(model_path, meta, **overrides)
    195     lang = meta.get("lang_factory", meta["lang"])
    196     cls = get_lang_class(lang)
--> 197     nlp = cls(meta=meta, **overrides)
    198     pipeline = meta.get("pipeline", [])
    199     factories = meta.get("factories", {})

~\Anaconda3\lib\site-packages\spacy\language.py in __init__(self, vocab, make_doc, max_length, meta, **kwargs)
    175         if make_doc is True:
    176             factory = self.Defaults.create_tokenizer
--> 177             make_doc = factory(self, **meta.get("tokenizer", {}))
    178         self.tokenizer = make_doc
    179         self.pipeline = []

~\Anaconda3\lib\site-packages\ginza\__init__.py in create_tokenizer(cls, nlp)
     48     @classmethod
     49     def create_tokenizer(cls, nlp=None):
---> 50         return SudachipyTokenizer(nlp)
     51 
     52     @classmethod

~\Anaconda3\lib\site-packages\ginza\sudachipy_tokenizer.py in __init__(self, nlp, mode, config_path)
     95         self.nlp = nlp
     96         self.vocab = nlp.vocab if nlp is not None else Vocab()
---> 97         dictionary = try_import_sudachipy_dictionary()
     98 
     99         split_mode = sudachipy_split_mode(mode)

~\Anaconda3\lib\site-packages\ginza\sudachipy_tokenizer.py in try_import_sudachipy_dictionary()
     38     except ImportError:
     39         raise ImportError(
---> 40             "Japanese support requires SudachiPy distributed with ja language model"
     41         )
     42 

ImportError: Japanese support requires SudachiPy distributed with ja language model

Thanks!

**Comment by hiroshi-matsuda-rit** [comment]
@pawar30 You should not install SudachiPy for GiNZA because it is installed along with GiNZA from the special package, after GiNZA v3.1.0.
https://github.com/megagonlabs/ginza#ginza-310
https://pypi.org/project/ja-ginza-dict/

Could you try `$ pip install -U ginza` again?

**Comment by pawar30** [comment]
Thank you for the suggestion @hiroshi-matsuda-rit . I tried this and it did not work(I also uninstalled sudachidict_core and uninstalled and re-installed Ginza).
From what I see, it looks to be a problem with dartsclone package. 

ImportError                               Traceback (most recent call last)
~\Anaconda3\lib\site-packages\ginza\sudachipy_tokenizer.py in try_import_sudachipy_dictionary()
     35     try:
---> 36         from sudachipy import dictionary
     37         return dictionary
~\Anaconda3\lib\site-packages\sudachipy\dictionary.py in <module>
     15 from . import config
---> 16 from . import dictionarylib
     17 from .dictionarylib.binarydictionary import BinaryDictionary
~\Anaconda3\lib\site-packages\sudachipy\dictionarylib\__init__.py in <module>
     18 from . import lexiconset
---> 19 from . import doublearraylexicon
     20 from . import dictionaryheader
~\Anaconda3\lib\site-packages\sudachipy\dictionarylib\doublearraylexicon.py in <module>
     16 
---> 17 from dartsclone import DoubleArray
     18 
ImportError: cannot import name 'DoubleArray' from 'dartsclone' (unknown location)

When I separately run 
```
import dartsclone
from dartsclone import DoubleArray
```

I get the same error message as above - cannot import name 'DoubleArray' from 'dartsclone' (unknown location).

I think this is some problem with the way dartsclone has been installed/compiled. When I download the zip folder from their git page, I see 2 files _dartsclone.pxd and _dartsclone.pyx which aren't there in my dartscloud package. Is this something to do not having cython installed? Sorry if I'm missing something basic here!

Regards,
Pranoti

**Comment by hiroshi-matsuda-rit** [comment]
Thanks for your detailed report. @pawar30 

>  Is this something to do not having cython installed? Sorry if I'm missing something basic here!

I tried to reproduce above error but it succeeded.
I think it might be a problem related with the runtime libraries.
Please try to install C++ build tools.
https://visualstudio.microsoft.com/ja/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16

**Comment by hiroshi-matsuda-rit** [comment]
Related issue is here.
https://github.com/rixwew/darts-clone-python/pull/9

**Comment by pawar30** [comment]
Issue resolved after installing C++ build Tools. Thank you @hiroshi-matsuda-rit !
