### ISSUE TITLE
Link "SudachiPy LICENSE PAGE" is 404

### ISSUE THREAD

**Issue by stomi80** [megagonlabs/ginza#12]
https://megagonlabs.github.io/ginza/
"SudachiPy LICENSE PAGE"からリンクしているURLが404です。
URLは https://github.com/WorksApplications/SudachiPy/blob/develop/LICENSE-2.0.txt です

**Comment by hiroshi-matsuda-rit** [comment]
satomi80-san,

Thanks for reporting about bad URL.
I revise them!
