### ISSUE TITLE
module 'ginza' has no attribute 'STOP_WORDS'

### ISSUE THREAD

**Issue by ivrschool** [megagonlabs/ginza#126]
----> 2 spacy_stop_words = ginza.STOP_WORDS
      3 len(spacy_stop_words)

AttributeError: module 'ginza' has no attribute 'STOP_WORDS'

Please help me fix this.

**Comment by hiroshi-matsuda-rit** [comment]
Please try following steps. Thanks. @ivrschool 
```
from spacy.lang import ja
stop_words = ja.STOP_WORDS
```

**Comment by ivrschool** [comment]
@hiroshi-matsuda-rit It worked for me. Thank You so much.
