### ISSUE TITLE
the era representation '令和' not included as an named entity labeled as 'Date'

### ISSUE THREAD

**Issue by tomohikoabe-gvatech** [megagonlabs/ginza#127]
I'm currently working on named entity recognition task using Ginza library, excellent NLP library.

I have a question.

When I try to locate and classify named entities in the text '令和1年12月1日から令和2年1月1日まで'  using Ginza library, I found that the recognized named entities don't include the era representation '令和' as following:
```
>>> import spacy
>>> spacy.__version__
'2.3.2'
>>> nlp = spacy.load('ja_ginza')
>>> text = '令和1年12月1日から令和2年1月1日まで'
>>> doc = nlp(text)
>>> [(ent.text, ent.label_) for ent in doc.ents]
[('1年12月1日', 'Date'), ('2年1月1日', 'Date')]
```
Could you tell me how to recognize the era representation '令和' as named entity in Ginza library. Any option or method?

I would really appreciate it if you could respond to my question.

**Comment by hiroshi-matsuda-rit** [comment]
Thank you for asking. @tomohikoabe-gvatech 
We're using UD_Japanese-BCCWJ v2.6 and GSK2014-A as training corpus of GiNZA v4.
We need to add some sentences containing 令和 for training corpus because the texts in BCCWJ are a little old and do not contain 令和.
We'd like to start discussing about updating the datasets with UD community, but it may take few months.

Or, you can use spaCy's EntityRuler for the pipeline of GiNZA.
Please read the API document below. 
https://spacy.io/usage/rule-based-matching#entityruler

**Comment by tomohikoabe-gvatech** [comment]
Thank you very much for kindly answering my question, @hiroshi-matsuda-rit san !

I try to use spaCy's EntityRuler as you taught me in the following way:
```
>>> import spacy
>>> import itertools
>>> from spacy.pipeline import EntityRuler
>>> nlp = spacy.load('ja_ginza')
>>> ruler = EntityRuler(nlp)
>>> patterns = [{"label": "Date", "pattern": f"令和{y}年{m}月{d}日"} for y, m, d in itertools.product(range(1, 100), range(1, 13), range(1, 32))]
>>> ruler.add_patterns(patterns)
>>> nlp.add_pipe(ruler)
>>>
>>> text = '令和1年1月1日'
>>> doc = nlp(text)
>>> [(ent.label_, ent.text) for ent in doc.ents]
[('Date', '令和1年1月1日')]
>>>
>>> text = '令和1年4月1日'
>>> doc = nlp(text)
>>> [(ent.label_, ent.text) for ent in doc.ents]
[('Date', '1年4月1日')]
```
In '令和1年1月1日', Ginza can correctly recognize '令和', but in '令和1年4月1日' cannot. 
I supose that It depends on the number of Year, Month, Day?  Or my `patterns` definition or usage of EntityRuler was wrong? 

I would really appreciate it if you could respond to my question.

**Comment by hiroshi-matsuda-rit** [comment]
This behavior is coming from the the conflict of GiNZA's NER and EntityRuler.
If you want to apply EntityRuler over NER, you need to change the order of components in pipeline.
Please see spaCy's document for more details.
https://spacy.io/api/language#add_pipe

**Comment by tomohikoabe-gvatech** [comment]
Thank you very much for answering my question !!
