### ISSUE TITLE
How to create meta.json from chive-1.1-mc90-20200318

### ISSUE THREAD

**Issue by YiAthena** [megagonlabs/ginza#134]
Hi, when I try to retrain ginza model with other corpus, I meet a problem. I am using the following code to train the model:
python -m spacy train ja ja_ginza-4.0.0 UD_Japanese-GSD/ja_gsd-ud-train.ne.json UD_Japanese-GSD/ja_gsd-ud-dev.ne.json -ovl 0.3 -n 100 -m ginza/meta.json.ginza -V 4.0.0
There are some warnings like:
UserWarning: [W022] Training a new part-of-speech tagger using a model with no lemmatization rules or data. This means that the trained model may not be able to lemmatize correctly. If this is intentional or the language you're using doesn't have lemmatization data, please ignore this warning. If this is surprising, make sure you have the spacy-lookups-data package installed. 
I guess these warnings are caused due to the lack of -b option. But when I try to use -b chive-1.1-mc90-20200318-a-unit-only/ , it says :
Could not read meta.json from chive-1.1-mc90-20200318-a-unit-only/meta.json
I am wondering how to get meta.json for chive-1.1-mc90? I would be very appreciate if I could get any information from you.

**Comment by YiAthena** [comment]
I am wondering whether the following solution is correct or not?
python -m spacy init-model ja models/ja_vectors_chive_mc90 --vectors-loc chive-1.1-mc90-20200318.txt.gz -t 500000

Also, I am not what is the difference between the following commands?
(1)python -m spacy train ja models/ja_gsd-2.3.0_all gsd26/ja_gsd-ud-train.ne.json gsd26/ja_gsd-ud-dev.ne.json **-v** models/ja_vectors_chive_mc90/
(2)python -m spacy train ja models/ja_gsd-2.3.0_all gsd26/ja_gsd-ud-train.ne.json gsd26/ja_gsd-ud-dev.ne.json **-b** models/ja_vectors_chive_mc90/

**Comment by hiroshi-matsuda-rit** [comment]
Thank you for asking. @YiAthena 

> python -m spacy init-model ja models/ja_vectors_chive_mc90 --vectors-loc chive-1.1-mc90-20200318.txt.gz -t 500000

It seems correct for me.
You may need to edit some fields of `models/ja_vectors_chive_mc90/meta.json`.
Please refer the attached `meta.json`, which I used for `ja_vectors_chive_mc90_35k/`, having specific settings for tokenizer.
[meta.json.txt](https://github.com/megagonlabs/ginza/files/5154827/meta.json.txt)

> Also, I am not what is the difference between the following commands?
> (2)python -m spacy train ja models/ja_gsd-2.3.0_all gsd26/ja_gsd-ud-train.ne.json gsd26/ja_gsd-ud-dev.ne.json -b models/ja_vectors_chive_mc90/

You need to use `-b` option of `spacy train` to inherit the entire settings in `models/ja_vectors_chive_mc90/meta.json` to the derived models. 
The `-v` option does not inherit anything other than vocab.

> UserWarning: [W022]

You can omit this warning. The Japanese model produces lemmatization by SudachiPy.

**Comment by YiAthena** [comment]
Thank you very much @hiroshi-matsuda-rit , I understand the problem.

**Comment by hiroshi-matsuda-rit** [comment]
Actually, we use SudachiPy mode=C and the retokenized version of UD_Japanese-BCCWJ as the training datasets.
Also, we expand the dependency labels of bunsetu head tokens with `_bunsetu` suffix in training datasets.
This bunsetu head suffix would be picked in BunsetuRecognizer in the pipeline and used for identifying the bunsetu heads in the analysis results.

Please read below code if you need to understand the GiNZA specific corpus settings.
https://github.com/megagonlabs/ginza/blob/develop/ginza_util/conllu_to_json.py

**Comment by hiroshi-matsuda-rit** [comment]
I'd like to close this issue. If you found any other questions, please reopen or create other issues.
