### ISSUE TITLE
Inappropriate bunsetu span detection caused by inconsistency between dependency structure and NE spans

### ISSUE THREAD

**Issue by tadashikumano** [megagonlabs/ginza#139]
Look at an example below:
```
# text = 去年秋から事故原因などの調査を再開した
1	去年	去年	NOUN	名詞-普通名詞-副詞可能	_	10	advmod	_	SpaceAfter=No|BunsetuBILabel=B|BunsetuPositionType=SEM_HEAD|NP_B|Reading=キョネン|NE=B-DATE|ENE=B-Date
2	秋	秋	NOUN	名詞-普通名詞-副詞可能	_	5	nmod	_	SpaceAfter=No|BunsetuBILabel=B|BunsetuPositionType=CONT|NP_B|Reading=アキ|NE=I-DATE|ENE=I-Date
3	から	から	ADP	助詞-格助詞	_	2	case	_	SpaceAfter=No|BunsetuBILabel=I|BunsetuPositionType=CONT|NP_I|Reading=カラ
4	事故	事故	NOUN	名詞-普通名詞-一般	_	5	compound	_	SpaceAfter=No|BunsetuBILabel=I|BunsetuPositionType=CONT|NP_I|Reading=ジコ
5	原因	原因	NOUN	名詞-普通名詞-サ変可能	_	8	nmod	_	SpaceAfter=No|BunsetuBILabel=I|BunsetuPositionType=SEM_HEAD|NP_I|Reading=ゲンイン
6	など	など	ADP	助詞-副助詞	_	5	case	_	SpaceAfter=No|BunsetuBILabel=I|BunsetuPositionType=SYN_HEAD|Reading=ナド
7	の	の	ADP	助詞-格助詞	_	5	case	_	SpaceAfter=No|BunsetuBILabel=I|BunsetuPositionType=SYN_HEAD|Reading=ノ
8	調査	調査	NOUN	名詞-普通名詞-サ変可能	_	10	obj	_	SpaceAfter=No|BunsetuBILabel=B|BunsetuPositionType=SEM_HEAD|NP_B|Reading=チョウサ
9	を	を	ADP	助詞-格助詞	_	8	case	_	SpaceAfter=No|BunsetuBILabel=I|BunsetuPositionType=SYN_HEAD|Reading=ヲ
10	再開	再開	VERB	名詞-普通名詞-サ変可能	_	0	root	_	SpaceAfter=No|BunsetuBILabel=B|BunsetuPositionType=ROOT|Reading=サイカイ
11	し	する	AUX	動詞-非自立可能	_	10	advcl	_	SpaceAfter=No|BunsetuBILabel=I|BunsetuPositionType=SYN_HEAD|Inf=サ行変格,連用形-一般|Reading=シ
12	た	た	AUX	助動詞	_	10	aux	_	SpaceAfter=No|BunsetuBILabel=I|BunsetuPositionType=SYN_HEAD|Inf=助動詞-タ,終止形-一般|Reading=タ
```
I've found that the token "秋" was first recognized as a bunsetu head as a result of dependency parsing, but was next canceled because the NE span "去年秋" exists which is inconsistent to the dependency structure, so finally the span "秋から" was not recognized as a bunsetu.
(Of course the main problem is that the head of '去年' is erroneously estimated by the dependency parsing, though.)
Such inconsistency between dependency structure and NE spans currently harms on bunsetu span detection, and I think there are two ways to relief it:
* Stop removal of bunsetu heads in NE spans when they are inconsistent to the dependency structure,
* Fix token dependencies to be consistent with NE spans.

**Comment by hiroshi-matsuda-rit** [comment]
@tadashikumano Thanks for pointing out.

> Fix token dependencies to be consistent with NE spans.

I think this is the optimal solution for current implementation.
I'd like to try to modify BunsetuRecognizer to ensure the consistency of bunsetu spans including ENTs, but it might take few days because it's a little complicated.

**Comment by hiroshi-matsuda-rit** [comment]
After consideration, I decided not taking above approaches because it is likely impossible to keep dependency parsing accuracy.
I'm going to drop the ENT spans which contain inconsistent dependencies, and then BunsetuRecognizer would identify correct heads from the dependency tree.

**Comment by hiroshi-matsuda-rit** [comment]
Finally, I refactored BusetuRecognizer as skipping bunsetu head adjustment procedure when inconsistent dependencies were found in named entity spans, but I kept all the ENT entries in doc to hold NER accuracy.
Your approach was right and effective. Thank you again! @tadashikumano

**Comment by tadashikumano** [comment]
Thank you very much.
The inconsistency is fundamentally a SpaCy's issue, and I think there is no need for too much complicated measures in Ginza.
