### ISSUE TITLE
Does Ginza have the capability of text normalization?

### ISSUE THREAD

**Issue by YiAthena** [megagonlabs/ginza#150]
Hi guys, I tried to search text normalization in Ginza project but failed. I want to know if I need  to normalize the text before using Ginza model for NER task. 
For example, in my current texts, there are some words like time : "30分" “1時間”, and also some words like "2回" "3丁目". 
For such cases, do I need to convert the numbers to Japanese characters?
If so, may I know which kind of format should I convert them to? Are there any cases or examples?

**Comment by YiAthena** [comment]
I tried Ginza with numbers, it looks like it can recognize normal numbers like below. But I am still wondering which function helps on it?
~  ginza
３番目
# text = ３番目
1	３	3	NUM	名詞-数詞	NumType=Card	2	nummod	_	SpaceAfter=No|BunsetuBILabel=B|BunsetuPositionType=CONT|NP_B|Reading=サン|NE=B-ORDINAL|ENE=B-Ordinal_Number
2	番目	番目	NOUN	接尾辞-名詞的-助数詞	_	0	root	_	SpaceAfter=No|BunsetuBILabel=I|BunsetuPositionType=ROOT|NP_I|Reading=バンメ|NE=I-ORDINAL|ENE=I-Ordinal_Number

**Comment by hiroshi-matsuda-rit** [comment]
Unfortunately, the GiNZA is not such powerful to solve this kind of general problems.
I recommend you to survey the following approaches.
http://www.cl.ecei.tohoku.ac.jp/index.php?Open%20Resources%2FnormalizeNumexp
https://www.anlp.jp/proceedings/annual_meeting/2012/pdf_dir/P3-4.pdf
