### ISSUE TITLE
Model training with nlp.update

### ISSUE THREAD

**Issue by its-ogawa** [megagonlabs/ginza#157]
I have a question about nlp.update.

I would like to perform eigenexpression extraction in GiNZA.

When I did eigenexpression extraction with the "ja_ginza" model, unintended tags appeared, so I used nlp.update to train them.

The learning target is learned as intended, but the tags that were available before the learning are lost.

Does nlp.update overwrite the training?
How can I perform additional learning?

For reference, here is the code we tried

test1:
```
import spacy
nlp = spacy.load('ja_ginza')
doc = nlp("今日の20時のバスで福岡市から宮崎市に移動します。")
for ent in doc.ents:
   print(ent.text, ent.start_char, ent.end_char, ent.label_)
```
result1:"宮崎市" is not "City".
```
20時 3 6 Time
福岡市 10 13 City
宮崎市 15 18 Government
```

test2:Learn "宮崎市" as "City".
```
import random
from spacy.util import minibatch, compounding

nlp = spacy.load('ja_ginza')

train_data = [
    ('宮崎市は、宮崎県の南東部にある市。宮崎県の県庁所在地で、中核市に指定されている。', 
        {'entities': [(0, 3, 'City'), ]}),
    ("【Go To Eatキャンペーン開催中】日本最大級のグルメサイト「食べログ」では、宮崎市で人気のお店 3311件を掲載中。", 
        {'entities': [(41, 44, 'City'), ]}),
    ("日南海岸は日向灘に面した宮崎市から串間市までの海岸で、その海岸線を走る国道220・448号は南国ムード満点のドライブコース。観光はもちろん海水浴やマリンスポーツのスポットも多い。", 
        {'entities': [(12, 15, 'City'), ]})
]

optimizer = nlp.begin_training()
n_iter = 100
for itn in range(n_iter):
    random.shuffle(train_data)
    # 学習処理
    batches = minibatch(train_data, 
                        size=compounding(4., 32., 1.001))
    losses = {}
    for batch in batches:
        texts, annotations = zip(*batch)
        nlp.update(texts, annotations, sgd=optimizer, drop=0.35, losses=losses)
        print('iteration'+str(itn)+': '+str(losses['ner']))

doc = nlp("今日の20時のバスで福岡市から宮崎市に移動します。")
for ent in doc.ents:
   print(ent.text, ent.start_char, ent.end_char, ent.label_)
```

result2:Only the training target is printed (why is that?)
```
宮崎市 15 18 City
```

**Comment by its-ogawa** [comment]
Let me add an explanation.

In the above example, we know that we can get the desired results by adding labels in EntityRuler.

More generally, we would like to know how to add more training so that the training of "ja_ginza" is not lost.

**Comment by hiroshi-matsuda-rit** [comment]
Sorry for late reply.
Simply, you need to add all the entities analyzed by `ja_ginza` model for all the training sentences.

For example, GiNZA v4 outputs below entities with ENE (Extended Name Entities) labels for a training sentence.
```
# text = 日本最大級のグルメサイト「食べログ」では、宮崎市で人気のお店 3311件を掲載中。
1       日本    日本    PROPN   名詞-固有名詞-地名-国   _       2       compound        _      SpaceAfter=No|BunsetuBILabel=B|BunsetuPositionType=CONT|NP_I|Reading=ニッポン|NE=B-GPE|ENE=B-Country
13      宮崎市  宮崎市  PROPN   名詞-固有名詞-地名-一般 _       22      nmod    _       SpaceAfter=No|BunsetuBILabel=B|BunsetuPositionType=SEM_HEAD|NP_I|Reading=ミヤザキシ|NE=B-ORG|ENE=B-Government
18      3311    3311    NUM     名詞-数詞       NumType=Card    19      nummod  _       SpaceAfter=No|BunsetuBILabel=I|BunsetuPositionType=CONT|NP_I|Reading=サンサンイチイチ|NE=B-QUANTITY|ENE=B-N_Event
19      件      件      NOUN    名詞-普通名詞-助数詞可能        _       22      obj     _      SpaceAfter=No|BunsetuBILabel=I|BunsetuPositionType=SEM_HEAD|NP_I|Reading=ケン|NE=I-QUANTITY|ENE=I-N_Event
```
The training data should contain all of these named entity spans with corresponding ENE labels.
```
{'entities': [(41, 44, 'Government'), (51, 56, 'N_Event'), ]}
```
If you need to change the label for "宮崎市" as "City", then:
```
{'entities': [(41, 44, 'City'), (51, 56, 'N_Event'), ]}
```

**Comment by its-ogawa** [comment]
Thank you for your answer.
I understand that I need to add all the entities for the training method.

However, for the result of ja_ginza, there are only a few entities that I want to change, and many would like to add more than overwrite.
We would appreciate it if you could accept it as one request.
In any case, GiNZA is still a great tool.
