### ISSUE TITLE
`IndexError: list assignment index out of range` for empty string

### ISSUE THREAD

**Issue by tamuhey** [megagonlabs/ginza#160]
The following line raises `IndexError` for empty string:

https://github.com/megagonlabs/ginza/blob/3ce56ed2a7fd13e1dc87fe5833c17f2178565d85/ginza/bunsetu_recognizer.py#L185

For example:

```
import spacy
nlp = spacy.load("ja_ginza")
nlp("")
```

**Comment by hiroshi-matsuda-rit** [comment]
@tamuhey Thank you for reporting the bug. I'm going to release v4.0.6 with this bug fix.
