### ISSUE TITLE
Use spacy v3

### ISSUE THREAD

**Issue by YuseiYokoyama** [megagonlabs/ginza#165]
ja_ginza model does not work with spaCy v3.
According to below url, models learned in spaCy v2 are not used in spaCy v3.
The best solution would be to retrain ja_ginza models using spaCy v3. 

https://github.com/explosion/spaCy/discussions/7054

**Comment by hiroshi-matsuda-rit** [comment]
Hi  Yokoyama-san,

Now We're working on developing GiNZA v5 which is based on spaCy v3 and spacy-transformers.
We also carry out ELECTRA pretraining to obtain higher accuracy than BERT.
Along with the transformers model, we'd like to release the standard GiNZA model based on spaCy v3.
Check out this slide if you need to understand our development approach in detail.
https://docs.google.com/presentation/d/1vJ-CeOwq0SG7KvjizjFOTh4A3-_nhY0b57NuKs-mow0/edit?usp=sharing

hiroshi
