### ISSUE TITLE
ginzame doesn't work

### ISSUE THREAD

**Issue by ShoSoejima** [megagonlabs/ginza#224]
Hi.

I'm new to GiNZA. I appreciate your work.

I tried `ginzame`, but it didn't work.

```
$ ginzame
 Traceback (most recent call last):
   ...
   ...
   File "/path/to/python3.9/site-packages/ginza/command_line.py", line 181, in set_nlp
     nlp = JapaneseTokenizer(nlp=Japanese(), split_mode=self.split_mode).tokenizer
 TypeError: __init__() got an unexpected keyword argument 'nlp'
```

The following is my environment.

- OS: Ubuntu 20.04
- Python 3.9.9
- ginza==5.0.3
- spacy==3.2.1

As the error message says, 'nlp' is unexpected here.
I've confirmed that replacing 'nlp' with 'vocab' fixes this problem, though I'm not sure it's the best way to fix this issue.

The change of JapaneseTokenizer was introduced by [this commit](https://github.com/explosion/spaCy/commit/c5de9b463a30dbb1cd016d4919e4348e55416d5c#diff-cf1fda066c32c67f5edfb9a3aabf776e8c886b4fa347f0256864424cdb759758L39-R41).

Thanks.

**Comment by hiroshi-matsuda-rit** [comment]
@ShoSoejima Thanks for reporting. Now, you can use ginzame with spaCy v3.2.x by upgrading GiNZA to v5.1.0.
The analysis speed of ginzame was improved dramatically not only by Sudachi.rs but also by improving the efficiency of parallel processing and output string stream generation.

**Comment by ShoSoejima** [comment]
@hiroshi-matsuda-rit 
Thanks for your reply.

I've upgraded GiNZA to v5.1.0 and now `ginzame` works fine!
Thank you!
