### ISSUE TITLE
Few entities not identified by ginza ner model, 3.1.2 pypi version

### ISSUE THREAD

**Issue by divyadilip91** [megagonlabs/ginza#247]
Hi team, 
While testing your japanese ner model using ginza 3.1.2, we noticed that few entities were not identified even after passing multiple texts having examples of those entities. Could you please help to check on this and help in resolving this issue and  tell what examples work for identifying the below mentioned entities.
1. Culture
2. Email
3. Game_Other
4. Digital_Game
5. Software
6. Show
7. Service
8. ID_number
9. Drug
10. Musical_Instrument
11. Phone_Number
12. Postal_Address
13. Family
14. Stock
15. Software
16. Virtual_Address
17. Virtual_Address_Other
18. URL

Thanks

**Comment by hiroshi-matsuda-rit** [comment]
Sorry for late reply. @divyadilip91 
The version which you're using is obsoleted and we cannot support them.
