### ISSUE TITLE
Format of data to train NER model

### ISSUE THREAD

**Issue by tringn** [megagonlabs/ginza#25]
Hi @hiroshi-matsuda-rit ,
Thanks for your great work.
I have a question on the format of data to train NER model.
Is data to train NER is the same as Spacy format?
```
[('cafebanyanは、表参道にある、ハワイをテーマにしたカフェなんだよ。', {'entities': [(19, 21, 'LOCATION')]}), ('青空に行ったら、二郎さんが大トロの握りをごちそうしてくれた。', {'entities': [(8, 9, 'PERSON')]
```
I looked into `train_ner.py` and found the format above is not suitable.
Can you help?
Thank you so much.

**Comment by hiroshi-matsuda-rit** [comment]
Sorry for late reply. @tringn 
I just started a refactoring for training procedure of GiNZA.
Could you please read the issue #26 and send me your opinion when I push some changes on NER training step.
Thanks a lot!

**Comment by hiroshi-matsuda-rit** [comment]
@tringn  I just decided to continue using ginza_util/train_ner.py after next version.

The input file format for train_ner.py is json, like below:
```
[
["４月にはイラン革命が起こり、親米のパフラヴィー朝に代わり、イスラム国家体制を謳うイラン・イスラム共和国が樹立された。", [[0, 2, "DATE"], [4, 7, "LOC"], [15, 16, "LOC"], [40, 51, "LOC"]]]
,
["この革命は国際政治・経済に大きな影響を与えた。", []]
,
["ここは、草津白根の登り口の直ぐしたです。", [[4, 8, "PERSON"]]]
]
```
You can use train_ner.py for the purpose of adapting to the target domains.
```
python -m ginza_util.train_ner -b ja_gsd-1.3.0/ target_domain_ner.json
```

**Comment by tringn** [comment]
@hiroshi-matsuda-rit 
Thanks. Your work helps me a lot.

**Comment by hiroshi-matsuda-rit** [comment]
@tringn We just release GiNZA v2.0.0.
https://github.com/megagonlabs/ginza/releases/tag/v2.0.0
Also we are proto-typing the spaCy official Japanese model and that model is trained by standard `spacy train` command.
Training json is created by using the script below.
https://github.com/megagonlabs/ginza/blob/develop/ginza_util/conllu_to_json.py
I hope these information will help you.

Thanks a lot!

**Comment by tringn** [comment]
@hiroshi-matsuda-rit 
Thank you very much.

**Comment by tringn** [comment]
@hiroshi-matsuda-rit 
Can you explain a little bit about https://github.com/megagonlabs/ginza/blob/develop/ginza_util/conllu_to_json.py
What is the format of input path. 
And more details about what optional options mean?
Thank you.
