### ISSUE TITLE
Release v2.0

### ISSUE THREAD

**Issue by hiroshi-matsuda-rit** [megagonlabs/ginza#26]
- Refactor the pipeline (almost done)
- Match the training procedure to spaCy's standard
- Release two versions (GSD and BCCWJ)

**Comment by hiroshi-matsuda-rit** [comment]
I'd start refactoring on GiNZA's training procedure from this commit:
https://github.com/megagonlabs/ginza/releases/tag/v1.2.1-gsd_preview-5

Please report the bugs and any other problems for this issue if you find. @KoichiYasuoka

**Comment by KoichiYasuoka** [comment]
Thank you for the new preview version, and I've found some questionable NOUNs (changed from VERB? ADJ?) as shown below:
```
for t in doc:
  print(t.i+1,t.orth_,t.lemma_,t.pos_,t.tag_,t._.inf,0 if t.head==t else t.head.i+1,t.dep_,t._.bunsetu_bi_label,t._.bunsetu_position_type)
1 美しく 美しい ADJ 形容詞,一般,*,* 形容詞,連用形-一般 2 acl B SEM_HEAD
2 教え 教える NOUN 動詞,一般,*,* 下一段-ア行,連用形-一般 5 obl B SEM_HEAD
3 、 、 PUNCT 補助記号,読点,*,* *,* 2 punct I CONT
4 楽しく 楽しい NOUN 形容詞,一般,*,* 形容詞,連用形-一般 5 obl B SEM_HEAD
5 教える 教える VERB 動詞,一般,*,* 下一段-ア行,終止形-一般 0 ROOT B ROOT
6 。 。 PUNCT 補助記号,句点,*,* *,* 5 punct I CONT
```

**Comment by hiroshi-matsuda-rit** [comment]
>In my humble opinion, 形容詞,連用形 can be regarded as ADV but not NOUN.

It's a kind of machine learning error. It would be better when I'll complete to refactor training procedure and create new models. Please test it again later. Thanks!

**Comment by hiroshi-matsuda-rit** [comment]
For naming issues, I'm using the names which are defined in UD-Japanese dataset, e.g. bunsetu-bi-label or bunsetu-position-type, for the extension fields of token. I'm not sure about whether it has right meaning but I'd like to use them as is for GiNZA.

**Comment by hiroshi-matsuda-rit** [comment]
GSD preview-6 just released.
Both tagging and dependency accuracy has been improved to the same level as ja_ginza_nopn-1.0.2.
https://github.com/megagonlabs/ginza/releases/tag/v1.3.0-gsd_preview-6

The example given by @KoichiYasuoka is now analyzed correctly. Please check it out.

**Comment by KoichiYasuoka** [comment]
Thank you very much again for your new v1.3.0-gsd_preview-6. The last example "美しく教え、楽しく教える。" now looks fine. Now I have another example:
```
for t in doc:
  print(t.i+1,t.orth_,t.lemma_,t.pos_,t.tag_,t._.inf,0 if t.head==t else t.head.i+1,t.dep_,t._.bunsetu_bi_label,t._.bunsetu_position_type)
1 こんにちは 今日は NOUN 感動詞-一般 *,* 7 nmod B SEM_HEAD
2 、 、 PUNCT 補助記号-読点 *,* 1 punct I CONT
3 赤ちゃん 赤ちゃん NOUN 名詞-普通名詞-一般 *,* 7 nmod B SEM_HEAD
4 、 、 PUNCT 補助記号-読点 *,* 3 punct I CONT
5 私 私 PRON 代名詞 *,* 7 nsubj B SEM_HEAD
6 が が ADP 助詞-格助詞 *,* 5 case I SYN_HEAD
7 ママ ママ NOUN 名詞-普通名詞-一般 *,* 0 ROOT B ROOT
8 よ よ PART 助詞-終助詞 *,* 7 mark I SYN_HEAD
9 。 。 PUNCT 補助記号-句点 *,* 7 punct I CONT
```
In this sentence `感動詞` might be INTJ with `discourse`. And, if possible, 赤ちゃん would be with `vocative`...

**Comment by KoichiYasuoka** [comment]
Thank you, @hiroshi-matsuda-rit san, I've just compared new "ja_nopn v1.3.1 preview-7" with "ja_gsd v1.3.0 preview-6".
```
for t in preview6("いつ頃終わる？"):
  print(t.i+1,t.orth_,t.lemma_,t.pos_,t.tag_,t._.inf,0 if t.head==t else t.head.i+1,t.dep_,t._.bunsetu_bi_label,t._.bunsetu_position_type)
1 いつ頃 何時頃 NOUN 名詞-普通名詞-副詞可能 *,* 2 advmod B SEM_HEAD
2 終わる 終わる VERB 動詞-非自立可能 五段-ラ行,終止形-一般 3 acl B SEM_HEAD
3 ？ ？ PUNCT 補助記号-句点 *,* 0 ROOT I ROOT

for t in preview7("いつ頃終わる？"):
  print(t.i+1,t.orth_,t.lemma_,t.pos_,t.tag_,t._.inf,0 if t.head==t else t.head.i+1,t.dep_,t._.bunsetu_bi_label,t._.bunsetu_position_type)
1 いつ頃 何時頃 ADV 名詞-普通名詞-副詞可能 *,* 2 advmod B SEM_HEAD
2 終わる 終わる VERB 動詞-非自立可能 五段-ラ行,終止形-一般 0 ROOT B ROOT
3 ？ ？ PUNCT 補助記号-句点 *,* 2 punct I CONT
```
preview-7 (BCCWJ-based) looks nice for this example, but preview-6 (GSD-based) illegally places `ROOT` on PUNCT. Umm...

**Comment by hiroshi-matsuda-rit** [comment]
memo
https://github.com/explosion/spaCy/issues/3818

**Comment by hiroshi-matsuda-rit** [comment]
Done. https://github.com/megagonlabs/ginza/releases/tag/v2.0.0
