### ISSUE TITLE
token.tag_ is not returning the pos tagging from Sudachi

### ISSUE THREAD

**Issue by mammalwong** [megagonlabs/ginza#27]
Hello, I found the pos tagging from token.pos_ and token.tag_ is returning the same universal pos tagging, is it possible to return the detailed pos tagging from Sudachi as token.tag_? Thanks.

**Comment by hiroshi-matsuda-rit** [comment]
Thanks for your report and sorry for may late reply.
GiNZA v2.0.0 will place Japanese pos tag value to token.tag_ entirely.
Please check it out!
https://github.com/megagonlabs/ginza/releases/tag/v2.0.0

**Comment by mammalwong** [comment]
Thank you very much!
