### ISSUE TITLE
Named Entity

### ISSUE THREAD

**Issue by wtberry** [megagonlabs/ginza#30]
Hello, thanks for amazing work, and is named entity recognition feature supported for ginza through `doc.ents`?

**Comment by hiroshi-matsuda-rit** [comment]
Sure. We applyed the KWDLC corpus for NER training phase.
http://nlp.ist.i.kyoto-u.ac.jp/index.php?KWDLC
But GiNZA's NER feature is not matured right now and I did not evaluate it deeply.
Please let us know by sending github issues when you'd find any analysis errors around NER.

Thanks a lot!
