### ISSUE TITLE
How to apply user dictionary?

### ISSUE THREAD

**Issue by HASHIMOTO-Takafumi** [megagonlabs/ginza#37]
> ginza-2.0.0 (2019-07-08)

> User dictionary available

To apply a configuration, you have to specify `config_path` here, I think.
設定を反映するにはここで`config_path`を指定する必要がありそうですが、どうでしょうか。他に方法があったらすいません。
https://github.com/megagonlabs/ginza/blob/e78a2bfa040e1e5668b31a703340b727ea53051a/ginza/sudachi_tokenizer.py#L54

cf.
https://github.com/WorksApplications/SudachiPy/blob/ac53e0d8a59ba88730eced805927ead5df5871ac/sudachipy/dictionary.py#L13

**Comment by hiroshi-matsuda** [comment]
It seems that the way in current sudachipy's configuration is not useful. I'd discuss this incovenience in issue of SudachiPy repository. Please wait few days. Thanks a lot!

**Comment by hiroshi-matsuda-rit** [comment]
I just added user dictionary section to README.md and Japanese index.md. Please read them. Thanks! @HASHIMOTO-Takafumi 
https://megagonlabs.github.io/ginza/#%E3%83%A6%E3%83%BC%E3%82%B6%E8%BE%9E%E6%9B%B8%E3%81%AE%E4%BD%BF%E7%94%A8
https://github.com/megagonlabs/ginza#user-dictionary

**Comment by HASHIMOTO-Takafumi** [comment]
I've made sure it works. Thanks a lot!
