### ISSUE TITLE
Question about JapaneseCorrector

### ISSUE THREAD

**Issue by ogis-uno** [megagonlabs/ginza#38]
Hi, I have a few question about JapaneseCorrector.

https://github.com/megagonlabs/ginza/blob/develop/ginza/japanese_corrector.py#L31

when token.head.i <  token.i, line 31 will always evaluated as True and return None. Is this correct implementation?

And one more, merge_range() returns begin, end, and head. 
But in correct_dep(), end is ignored, and merged with fixed range between begin and begin+2.

I can't figure out whether these are problems or not now.
If these are correct implementation, sorry for bothering you.

**Comment by hiroshi-matsuda-rit** [comment]
Hi @ogis-uno, Thank you for asking about the details of JapaneseCorrector.

The behavior of merge_range() is expected but actually correct_dep() is not correct.
I'm going to revise that.

Thnak you so much!

**Comment by hiroshi-matsuda-rit** [comment]
I fixed this issue in #67. Thank you for reporting the problems.
