### ISSUE TITLE
request: comparison to other tokenizers/PoS taggers

### ISSUE THREAD

**Issue by MastafaF** [megagonlabs/ginza#41]
Hi,

In this thread [https://github.com/taishi-i/nagisa/issues/6 ](url) they discuss a comparison between several tokenizers. The conclusion drawn is the following: 

> F1-scores
> KyTea > nagisa > SudachiPy > MeCab
> Speed
> MeCab > KyTea > nagisa > SudachiPy
>

I also think users would greatly benefit from knowing things like parsing speed comparisons, accuracy, and other slight differences/nuances/use cases.

Best,

**Comment by KoichiYasuoka** [comment]
I've just tried tentative benchmark by the test set of [UD_Japanese-PUD](https://github.com/UniversalDependencies/UD_Japanese-PUD) with [CoNLL 2018 Shared Task](http://universaldependencies.org/conll18/) evaluation.

<table>
<tr><td></td><th>LAS</th><th>MLAS</th><th>BLEX</th><td>time</td></tr>
<tr><td>ufal.UDPipe</td><td>81.14</td><td>69.00</td><td>71.34</td><td>37.813</td></tr>
<tr><td>StanfordNLP</td><td>74.38</td><td>59.63</td><td>62.06</td><td>143.531</td></tr>
<tr><td>NLP-Cube</td><td>73.71</td><td>57.03</td><td>60.68</td><td>883.484</td></tr>
<tr><td>GiNZA</td><td>63.49</td><td>43.05</td><td>43.54</td><td>42.906</td></tr>
<tr><td>unidic2ud</td><td>46.37</td><td>31.28</td><td>29.31</td><td>29.156</td></tr>
</table>

* [ufal.UDPipe](https://pypi.org/project/ufal.udpipe/) 1.2.0.2 with [japanese-gsd-ud-2.4-190531.udpipe](http://hdl.handle.net/11234/1-2998)
* [StanfordNLP](https://pypi.org/project/stanfordnlp/) 0.2.0 with [ja_gsd 0.2.0](https://stanfordnlp.github.io/stanfordnlp/models.html)
* [NLP-Cube](https://pypi.org/project/nlpcube/) 0.1.0.7 with ja-1.1
* GiNZA 2.0.0
* [unidic2ud](https://pypi.org/project/unidic2ud/) 1.0.1 with UniDic "gendai" and UDPipe "japanese-gsd"

However, the evaluation was done with `UPOS` and `DEPREL` without `XPOS`. Well, @MastafaF, do you know any other python-based UD-parser for Japanese?

**Comment by KoichiYasuoka** [comment]
Another benchmark with the test set of [UD_Japanese-Modern](https://github.com/UniversalDependencies/UD_Japanese-Modern):

<table>
<tr><td></td><th>LAS</th><th>MLAS</th><th>BLEX</th><td>time</td></tr>
<tr><td>unidic2ud</td><td>55.48</td><td>32.99</td><td>21.90</td><td>11.224</td></tr>
<tr><td>GiNZA</td><td>43.95</td><td>22.03</td><td>21.27</td><td>14.044</td></tr>
<tr><td>NLP-Cube</td><td>30.41</td><td>14.01</td><td>16.97</td><td>203.920</td></tr>
<tr><td>StanfordNLP</td><td>29.37</td><td>12.13</td><td>15.19</td><td>104.740</td></tr>
<tr><td>ufal.UDPipe</td><td>27.73</td><td>11.56</td><td>13.91</td><td>12.024</td></tr>
</table>

* [unidic2ud](https://pypi.org/project/unidic2ud/) 1.0.4 with UniDic "qkana" and UDPipe "japanese-gsd"
* GiNZA 2.0.0
* [NLP-Cube](https://pypi.org/project/nlpcube/) 0.1.0.7 with ja-1.1
* [StanfordNLP](https://pypi.org/project/stanfordnlp/) 0.2.0 with [ja_gsd 0.2.0](https://stanfordnlp.github.io/stanfordnlp/models.html)
* [ufal.UDPipe](https://pypi.org/project/ufal.udpipe/) 1.2.0.2 with [japanese-gsd-ud-2.4-190531.udpipe](http://hdl.handle.net/11234/1-2998)

**Comment by MastafaF** [comment]
Hi @KoichiYasuoka,
Thank you for your answer and the interesting comparison. 
Prior to that, I have been using **Mecab** with **Neologd**  
 - dictionary containing neologisms - and **StanforNLP**, both in python. Hence, I wanted to compare Ginza tool with those Tokenizer systems. 
I used both Ginza and Mecab with **ipadic** dictionary on **Wikipedia** dump and I noticed several differences in the outputs. 

**Ginza Output:** 
> アンパサンド
アンパサンド (&、英語名：) とは並立助詞「…と…」を意味する記号である。ラテン語の の合字で、Trebuchet MSフォントでは、と表示され "et" の合字であることが容易にわかる。ampersa、すなわち "and per se and"、その意味は"and [the symbol which] by itself [is] and"である。
その使用は1世紀に遡ることができ、5世紀中葉から現代に至るまでの変遷がわかる。
Z に続くラテン文字アルファベットの27字目とされた時期もある。"

**Mecab Output:** 
>アンパサンド
アンパサンド (&、 英語 名 ：) と は 並立 助詞 「 … と … 」 を 意味 する 記号 で ある 。 ラテン語 の の 合 字 で 、 Trebuchet MS フォント で は 、 と 表示 さ れ " et " の 合 字 で ある こと が 容易 に わかる 。 ampersa 、 すなわち " and per se and "、 その 意味 は " and [ the symbol which ] by itself [ is ] and " で ある 。
その 使用 は 1 世紀 に 遡る こと が でき 、 5 世紀 中葉 から 現代 に 至る まで の 変遷 が わかる 。
Z に 続く ラテン 文字 アルファベット の 27 字 目 と さ れ た 時期 も ある 。 


It would seem to me that Mecab Output is of **better quality.** 
What is your view with this respect? (I kept SudachiPy when using Ginza with spacy)

**Comment by KoichiYasuoka** [comment]
Well, @MastafaF, your output of GiNZA seems different from mine.
```py
>>> import spacy
>>> ja=spacy.load("ja_ginza")
>>> s=ja('アンパサンド (&、英語名：) とは並立助詞「…と…」を意味する記号である。ラテン語 の の合字で、Trebuchet MSフォントでは、と表示され"et"の合字であることが容易にわかる。ampersa、すなわち "and per se and"、その意味は"and [the symbol which] by itself [is] and"である。その使用は1世紀に遡ることができ、5世紀中葉から現代に至るまでの変遷がわかる。Zに続くラテン文字アルファベットの27字目とされた時期もある。')
>>> print(" ".join(" ".join(str(t) for t in u) for u in s.sents))
アンパサンド ( & 、 英語 名 ： ) と は 並立 助詞 「 … と … 」 を 意味 する 記 号 で ある 。 ラテン語 の の 合字 で 、 Tre bu chet MS フォント で は 、 と 表示 さ れ " et " の 合字 で ある こと が 容易 に わかる 。 ampersa 、 すなわち " and per se and " 、 その 意味 は " and [ the symbol which ] by it self [ is ] and " で ある 。 その 使用 は 1 世紀 に 遡る こと が でき 、 5 世紀 中葉 から 現代  に 至る まで の 変遷 が わかる 。 Z に 続く ラテン 文字 アルファベット の 27 字 目 と さ れ た 時期 も ある 。
```
Please clarify what you compared and what you did in your comparison.

**Comment by MastafaF** [comment]
Hi @KoichiYasuoka , 

Sorry there was a mistake in my prior message. There you have a comparison of **Mecab** and **Ginza**:

**Input**
> txt = u'アンパサンド (&、英語名：) とは並立助詞「…と…」を意味する記号である。ラテン語の の合字で、Trebuchet MSフォントでは、と表示され "et" の合字であることが容易にわかる。ampersa、すなわち "and per se and"、その意味は"and [the symbol which] by itself [is] and"である。'

**Ginza Code and Output:**
`import spacy
nlp_ja = spacy.load('ja_ginza')
doc_ja = nlp_ja(txt)
tokens = [token.orth_ for token in doc_ja]
string = " ".join(tokens)
print(string)`

> アンパサンド 
  アンパサンド ( & 、 英語 名 ： ) と は 並立 助詞 「 … と … 」 を 意味 する 記号 で ある 。 ラテン語 の の 合字 で 、 Tre bu chet MS フォント で は 、 と 表示 さ れ " et " の 合字 で ある こと が 容易 に わかる 。 ampersa 、 すなわち " and per se and " 、 その 意味 は " and [ the symbol which ] by it self [ is ] and " で ある 。 その 使用 は 1 世紀 に 遡る こと が でき 、 5 世紀 中葉 から 現代 に 至る まで の 変遷 が わかる 。 Z に 続く ラテン 文字 アルファベット の 27 字 目 と さ れ た 時期 も ある 。


**Mecab Code and Output:**
`import MeCab
tagger = MeCab.Tagger("-Owakati")
print (tagger.parse(txt).strip()+"\n")`

> アンパサンド アンパサンド (&、 英語 名 ：) と は 並立 助詞 「 … と … 」 を 意味 する 記号 で ある 。 ラテン語 の の 合 字 で 、 Trebuchet MS フォント で は 、 と 表示 さ れ " et " の 合 字 で ある こと が 容易 に わかる 。 ampersa 、 すなわち " and per se and "、 その 意味 は " and [ the symbol which ] by itself [ is ] and " で ある 。 その 使用 は 1 世紀 に 遡る こと が でき 、 5 世紀 中葉 から 現代 に 至る まで の 変遷 が わかる 。 Z に 続く ラテン 文字 アルファベット の 27 字 目 と さ れ た 時期 も ある 。


Again, contrary to the recommendation in the github frontpage: 
> Remove sudachipy related directories
> SudachiPy and its dictionary are installed via pip during ginza installation

I kept **SudachiPy** dictionary for Ginza.  I don't know exactly the consequence of that in the Tokenization performance. If you have any insight, please let me know.

**Comment by KoichiYasuoka** [comment]
I understand that GiNZA is tokenizer, POS-tagger, lemmatizer, and dependency-parser for Japanese. GiNZA's tokenizer is verfy fine-tuned for the purpose, especially for POS-tagger and its dependency-parser, after its `JapaneseCorrector`. It seems nonsense for me to compare GiNZA's tokenizer performance for some other purposes.

**Comment by MastafaF** [comment]
Did you keep **SudachiPy** in your installation of Ginza. And why do you think we should remove it? 

Don't you think that **Ginza** would benefit from a dictionary of Japanese **neologisms** like the one **Mecab** is using?

**Comment by KoichiYasuoka** [comment]
Sorry, @MastafaF, I don't think [mecab-ipadic-NEologd](https://github.com/neologd/mecab-ipadic-neologd/blob/master/README.ja.md) is suitable for dependency-parsing under [Universal Dependencies](https://universaldependencies.org/u/dep/flat.html), especially in the treatment of multiword expressions such as 中居正広の金曜日のスマイルたちへ. Please scrutinize the example of "The Lord of The Rings" on [Universal Dependencies](https://universaldependencies.org/u/dep/flat.html) and the treatment of multiword named entities on [spaCy](https://spacy.io/usage/linguistic-features#named-entities).

![kinsma](https://user-images.githubusercontent.com/15098598/64135179-b5730480-ce20-11e9-8cf3-d21fdd734b23.png)

**Comment by hiroshi-matsuda-rit** [comment]
@MastafaF Thanks for discussing the performance of GiNZA and the rivals. Actually, the GiNZA and the Stnaford NLP are the dependency parsers hence we're focusing to improve the parsing performance. If you do need only the tokenization functionality (not the parsing), you should use mecab, sudachi or kytea directly.

@KoichiYasuoka Thank you for giving the comparison among the Japanese UD parsers. The NINJAL is re-annotating the PUD and GSD corpora with their own guidelines. Could you please evaluate the accuracy of GiNZA with the updated corpora?

In addition, I published a slide for the Universal Dependency Symposium held on Sep. 4 at NINJAL. I hope it helps understanding the purpose of Japanese UD researches and the motivations for developing the GiNZA.
https://www.slideshare.net/MegagonLabs/ginza-cabocha-udpipe-stanford-nlp
