### ISSUE TITLE
Parsing/Tokenizing a file with Ginza from command line

### ISSUE THREAD

**Issue by MastafaF** [megagonlabs/ginza#60]
Hi, Ginza is primarily used as a  dependency parser. However, it can also be used for tokenization. Hence, I would like to know if there is a **command line interface** similar to Jieba for tokenizing a file. 

In **Jieba**, we can use: 
`python -m jieba -d filename `

How could we do that using Ginza? :)

Kind Regards,

**Comment by hiroshi-matsuda-rit** [comment]
@MastafaF It is typical use-case of GiNZA. I'd like to add the tokenization mode for `command_line.py` in next release. Thank you!

**Comment by hiroshi-matsuda-rit** [comment]
@MastafaF Please try to use sudachipy command, which is installed together with ginza, if you need to.
Or, do you need --delimiter option like Jieba?
Actually, I don't want to add that for ginza command.
I'm planning to add a format option which provides MeCab compatible output format.
https://taku910.github.io/mecab/

**Comment by MastafaF** [comment]
I am just looking for a way to tokenize a txt file with Ginza/Sudachipy as in mecab: 
`% mecab INPUT -o OUTPUT`

It is not clear how to do it or if it is possible to do it currently from command line.

**Comment by hiroshi-matsuda-rit** [comment]
Please try to use `ginzame` command in v3.0.0.
Thank you! @MastafaF
