### ISSUE TITLE
Named entity didn't work on GPU

### ISSUE THREAD

**Issue by fortharrow** [megagonlabs/ginza#96]
I used Ginza with GPU for making some named entities but the output was empty.
Also tried CPU only operation, it worked.

Named entity with GPU on Ginza or Spacy is not supported ?

**Comment by fortharrow** [comment]
I tried Ginza on Google Colab with GPU works well.
It seems that this depends on driver version or so ...

**Comment by hiroshi-matsuda-rit** [comment]
@fortharrow Thank you for reporting the inconsistent outputs between CPU and GPU.
I'll make some tests to reproduce it while releasing v4.

**Comment by fortharrow** [comment]
Thank you for your reply.
I am using Spacy on Windows and some bugs are found before like below on GPU.
https://github.com/explosion/spaCy/issues/4758

I am a little bit afraid of this kind of bug occurred on GiNZA now ...
